python3 attribute_error.py